Convert all the existing layers to use the builder pattern
oxidized-transformers/oxidized-transformers pull request #13
Opened 2024-02-16 09:50 UTC by danieldk

We have two important design desiderata:

1. We want layers in models to be configurable, so that it is possible to make custom architectures using composition.

This was largely archieved in Curated Transformers by letting modules take other modules in the constructor parameters. However in Oxidized Transformers, this solution conflicts with:

2. Layers must construct their childeren, to have control over their namespacing.

In Curated Transformers, we could rely on PyTorch' module abstraction for namespacing. However, this does not work in Candle, since we have to provide a layer's prefix when constructing it.

So, instead we settle on a design that uses builders. Rather than directly building models, we build configuration structures (though they could also be called uninstantiated model graphs). Each configuration struct has a build method to create the corresponding module. This fulfills the second desideratum by letting a module build method also construct it's children by calling their build methods.

We fulfill the first desideratum by having each configuration take its childern as a type-generic boxed struct. For instance, the self-attention struct can have a generic layer norm in this way:

```rust
pub struct SelfAttentionConfig {
  layer_norm: Box<dyn BuildModule>,

  // ...
}
```

Any kind of layer configuration can be plugged in as the layer norm, as long as it implements the `BuildModule` trait.

This change updates all the existing layers to this pattern. After this change, each layer is generaly implemented as:

- A layer configuration struct.
- A `Default` implementation for the configuration.
- Setting methods following the builder pattern: allows named setting, but in contrast to public struct members, we can modify the struct fields.
- An implementation of the `BuildModule` trait, or a similar trait if it does not fit the signature of `BuildModule`
- A layer struct.
- Implementation of `ModuleT` or another trait.

Not all the layers have all of these parts. E.g. the rotary embeddings layers are not fully generic. Since they are strongly bound to the self-attention implementation, we don't expect downstream users to plug different implementations. Or in the case of embeddings, I still need to think about the proper abstraction level.

The changeset also contains a small number of unrelated fixes, such as some instances where we need to use broadcast multiplication. This is not ideal, but since this change reimplements all the layers, it was hard to separate these fixes.

**Note:** some parts are not completely perfect or crystalized yet, but I wanted to get this out before the Llama branch becomes even harder to untangle.

2024-02-16 19:55 UTC, shadeMe requested changes
The main comments are the first few ones - question about `store_cache` and a doc typo.

The rest have to do with removing the `Set...` prefix in config builder methods. Feel free to ignore them, as I only realized later that it would've made more sense to just add that prefix to the few configs that didn't have it 😅

LGTM otherwise 🎉

2024-02-16 19:55 UTC, shadeMe commented on src/architectures/decoder.rs
> +    /// * `input` - Hidden representations to apply the layer to.
```suggestion
    /// * `piece_ids` - Hidden representations to apply the layer to.
```

2024-02-16 19:55 UTC, shadeMe commented on src/architectures/decoder.rs
> +        store_cache: bool,
Don't we want to remove this and just always update the cache if it's passed to `forward`?

2024-02-16 19:55 UTC, shadeMe commented on src/architectures/encoder.rs
> +    /// * `input` - Hidden representations to apply the layer to.
```suggestion
    /// * `piece_ids` - Hidden representations to apply the layer to.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/attention/mod.rs
> +    /// Returns: hidden representations after attention.
```suggestion
    /// Returns: Hidden representations after attention.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/attention/self_attention.rs
> +    /// Layer norm.
```suggestion
    /// Layer norm applied to the input.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/attention/self_attention.rs
> +    /// Number of query heads.
```suggestion
    /// Configuration for rotary embeddings.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/attention/self_attention.rs
> +    /// Default: `12`.
```suggestion
    /// Default: `None`.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/embeddings/qk_rotary_embeddings.rs
> +#[derive(Debug)]
```suggestion
#[derive(Debug, Clone)]
```
Just adding clone wherever it makes sense for the configs.

2024-02-16 19:55 UTC, shadeMe commented on src/layers/embeddings/qk_rotary_embeddings.rs
> +    /// Set the base used for `theta`.
```suggestion
    /// Base used for `theta`.
```
To keep it consistent with the builder methods elsewhere.

2024-02-16 19:55 UTC, shadeMe commented on src/layers/embeddings/qk_rotary_embeddings.rs
> +    /// Set the fraction of the hidden width to apply rotary embeddings to.
```suggestion
    /// Fraction of the hidden width to apply rotary embeddings to.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/embeddings/qk_rotary_embeddings.rs
> +    /// Set the head width for query and key attention.
```suggestion
    /// Head width for query and key attention.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/embeddings/qk_rotary_embeddings.rs
> +    /// Set the number of positions to precompute rotary embeddings for.
```suggestion
    /// Number of positions to precompute rotary embeddings for.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/embeddings/rotary_embeddings.rs
> +    /// Set the width of the rotary embeddings.
```suggestion
    /// Width of the rotary embeddings.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/embeddings/rotary_embeddings.rs
> +    /// Set the number of positions to precompute rotary embeddings for.
```suggestion
    /// Number of positions to precompute rotary embeddings for.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/embeddings/rotary_embeddings.rs
> +    /// Set the base used for `theta`.
```suggestion
    /// Base used for `theta`.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    /// Set the dropout to apply to the embeddings.
```suggestion
    /// Dropout to apply to the embeddings.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    /// Set the layer normalization to apply to the embeddings.
```suggestion
    /// Layer normalization to apply to the embeddings.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    /// Set the width of the embeddings.
```suggestion
    /// Width of the embeddings.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    /// Set the width of the transformer.
```suggestion
    /// Width of the transformer.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    /// Set the number of position embeddings.
```suggestion
    /// Number of position embeddings.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    /// Set the vocabulary size (number of embeddings).
```suggestion
    /// Vocabulary size (number of embeddings).
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    /// Set the token type vocabulary size (number of token type embeddings).
```suggestion
    /// Token type vocabulary size (number of token type embeddings).
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    /// Set the dropout to apply after embedding projection.
```suggestion
    /// Dropout to apply after embedding projection.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    /// Set the layer normalization to apply to the projection layer.
```suggestion
    /// Layer normalization to apply to the projection layer.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +        source: Box<dyn std::error::Error + Send + Sync>,
```suggestion
        source: BoxedError,
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +        source: Box<dyn std::error::Error + Send + Sync>,
```suggestion
        source: BoxedError,
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/layer.rs
> +    /// Set the attention residual connection layer norm.
```suggestion
    /// Attention residual connection layer norm.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/layer.rs
> +    /// Set the attention layer configuration.
```suggestion
    /// Attention layer configuration.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/layer.rs
> +    /// Set the feed-forward layer configuration.
```suggestion
    /// Feed-forward layer configuration.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/layer.rs
> +    /// Set the feed-forward residual connection layer norm.
```suggestion
    /// Feed-forward residual connection layer norm.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/layer.rs
> +    /// Set the parallel attention dropout.
```suggestion
    /// Parallel attention dropout.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/layer.rs
> +    /// Set whether to use parallel attention.
```suggestion
    /// Whether to use parallel attention.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    #[snafu(display("Cannot build layer norm module"))]
```suggestion
    #[snafu(display("Cannot build layer norm"))]
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/transformer/embeddings.rs
> +    #[snafu(display("Cannot build dropout module"))]
```suggestion
    #[snafu(display("Cannot build dropout"))]
```
For consistency, as seen elsewhere.

2024-02-16 19:55 UTC, shadeMe commented on src/layers/activation.rs
> +    /// [Hendrycks and Gimpel, 2016](https://arxiv.org/abs/1606.08415)
```suggestion
    /// See [Hendrycks and Gimpel, 2016](https://arxiv.org/abs/1606.08415).
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/activation.rs
> +    /// [Fukushima, 1969](https://ieeexplore.ieee.org/document/4082265)
```suggestion
    /// See [Fukushima, 1969](https://ieeexplore.ieee.org/document/4082265).
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/activation.rs
> +    /// [Hendrycks and Gimpel, 2016](https://arxiv.org/abs/1606.08415)
```suggestion
    /// See [Hendrycks and Gimpel, 2016](https://arxiv.org/abs/1606.08415).
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/dropout.rs
> +    /// Set the dropout probability.
```suggestion
    /// Dropout probability.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/feedforward.rs
> +    /// Set the activation function.
```suggestion
    /// Activation function.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/feedforward.rs
> +    /// Set the dropout to apply after the feed-forward layer.
```suggestion
    /// Dropout to apply after the feed-forward layer.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/feedforward.rs
> +    /// Set the hidden width of the transformer.
```suggestion
    /// Hidden width of the transformer.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/feedforward.rs
> +    /// Set the intermediate width in the feed-forward layer.
```suggestion
    /// Intermediate width in the feed-forward layer.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/feedforward.rs
> +    /// Set the layer normalization module.
```suggestion
    /// Layer normalization module.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/layer_norm.rs
> +    /// Set whether to use an affine transformation.
```suggestion
    /// Whether to use an affine transformation.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/layer_norm.rs
> +    /// Set the epsilon value.
```suggestion
    /// Epsilon value.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/layer_norm.rs
> +    /// Set whether to remove the mean.
```suggestion
    /// Whether to remove the mean.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/layer_norm.rs
> +    /// Set the dimensionality of the layer.
```suggestion
    /// Dimensionality of the layer.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/layer_norm.rs
> +    /// Set the epsilon value.
```suggestion
    /// Epsilon value.
```

2024-02-16 19:55 UTC, shadeMe commented on src/layers/layer_norm.rs
> +    /// Set the dimensionality of the layer.
```suggestion
    /// Dimensionality of the layer.
```

2024-02-17 08:18 UTC, danieldk commented on src/architectures/decoder.rs
> +        store_cache: bool,
Indeed, removed this argument.

2024-02-17 08:45 UTC, danieldk commented
> The rest have to do with removing the Set... prefix in config builder methods. Feel free to ignore them, as I only realized later that it would've made more sense to just add that prefix to the few configs that didn't have it 😅

I am fine with it either way. Removing the _Set..._ makes it sound more declarative, which I like.

2024-02-17 15:04 UTC, shadeMe approved these changes

2024-02-17 15:04 UTC, merged